python -m pip3 install --upgrade pip

pip3 install asn1crypto
pip3 install beautifulsoup4
pip3 install certifi
pip3 install chardet
pip3 install cmake
pip3 install cryptography
pip3 install cycler
pip3 install idna
pip3 install joblib
pip3 install keyring
pip3 install keyrings.alt
pip3 install kiwisolver
pip3 install matplotlib
pip3 install numpy
pip3 install pandas
pip3 install pillow
pip3 install pip
pip3 install pycrypto
pip3 install pygobject
pip3 install pyparsing
pip3 install python-apt
pip3 install pytz
pip3 install pyxdg
pip3 install requests
pip3 install scikit-learn
pip3 install scipy
pip3 install secretstorage
pip3 install selenium
pip3 install setuptools
pip3 install six
pip3 install soupsieve
pip3 install ssh-import-id
pip3 install threadpoolctl
pip3 install unattended-upgrades
pip3 install urllib3
pip3 install wheel
pip3 install xgboost
